stages:
  Preprocess:
    cmd: python ./src/training/process_data.py
    deps:
    - .\data\raw\titanic.csv
    - .\src\training\process_data.py
    outs:
    - .\data\processed\titanic-test.parquet
    - .\data\processed\titanic-train.parquet
  Train:
    cmd: python ./src/training/train.py
    deps:
    - .\data\processed\titanic-test.parquet
    - .\data\processed\titanic-train.parquet
    - .\src\training\train.py
    outs:
    - .\models\Titanic_Classifier\label_encoder.pkl
    - .\models\Titanic_Classifier\preprocessors.pkl
    - .\models\Titanic_Classifier_random_forest\Titanic_Classifier_random_forest_model.pkl
    - .\models\Titanic_Classifier_random_forest\Titanic_Classifier_random_forest_pipeline.pkl
    - .\models\Titanic_Classifier_xgboost\Titanic_Classifier_xgboost_model.pkl
    - .\models\Titanic_Classifier_xgboost\Titanic_Classifier_xgboost_pipeline.pkl
  Evaluate:
    cmd: python ./src/training/evaluate.py
    deps:
    - .\data\processed\titanic-test.parquet
    - .\models\Titanic_Classifier\label_encoder.pkl
    - .\models\Titanic_Classifier_random_forest\Titanic_Classifier_random_forest_pipeline.pkl
    - .\models\Titanic_Classifier_xgboost\Titanic_Classifier_xgboost_pipeline.pkl
    - .\src\training\evaluate.py
    outs:
    - .\reports\Titanic_Classifier_random_forest\evaluation_report.json
    - .\reports\Titanic_Classifier_xgboost\evaluation_report.json