stages:
  Preprocess:
    cmd: python ./src/training/process_data.py
    deps:
    - .\data\raw\titanic.csv
    - .\src\training\process_data.py
    outs:
    - .\data\processed\titanic-test.parquet
    - .\data\processed\titanic-train.parquet
  Train:
    cmd: python ./src/training/train.py
    deps:
    - .\data\processed\titanic-test.parquet
    - .\data\processed\titanic-train.parquet
    - .\src\training\train.py
    outs:
    - .\models\Titanic_Classifier\label_encoder.pkl
    - .\models\Titanic_Classifier\feature_preprocessor.pkl
    - .\models\Titanic_Classifier\preprocessor.pkl
    - .\models\Titanic_Classifier\preprocessors.pkl
    - .\models\Titanic_Classifier_randomforestclassifier\Titanic_Classifier_randomforestclassifier_model.pkl
    - .\models/Titanic_Classifier_randomforestclassifier/Titanic_Classifier_randomforestclassifier_pipeline.pkl
    - .\models\Titanic_Classifier_xgbclassifier\Titanic_Classifier_xgbclassifier_model.pkl
    - .\models\Titanic_Classifier_xgbclassifier\Titanic_Classifier_xgbclassifier_pipeline.pkl
  Evaluate:
    cmd: python ./src/training/evaluate.py
    deps:
    - .\data\processed\titanic-test.parquet
    - .\models\Titanic_Classifier\label_encoder.pkl
    - .\models/Titanic_Classifier_randomforestclassifier/Titanic_Classifier_randomforestclassifier_pipeline.pkl
    - .\models\Titanic_Classifier_xgbclassifier\Titanic_Classifier_xgbclassifier_pipeline.pkl
    - .\src\training\evaluate.py
    
    outs:
    - .\reports\Titanic_Classifier_random_forest\evaluation_report.json
    - .\reports\Titanic_Classifier_xgboost\evaluation_report.json