stages:
  preprocess:
    cmd: python ./src/training/process_data.py
    deps:
    - .\data\raw\titanic.csv
    - .\src\training\process_data.py
    outs:
    - .\data\processed\titanic-test.parquet
    - .\data\processed\titanic-train.parquet
    
  Train:
    cmd: python ./src/training/train.py
    deps:
    - .\data\processed\Titanic-test.parquet
    - .\data\processed\Titanic-train.parquet
    - .\src\training\train.py
    outs:
    - .\models\Titanic_Classifier\label_encoder.pkl
    - .\models\Titanic_Classifier_random_forest\Titanic_Classifier_random_forest_model.pkl
    - .\models\Titanic_Classifier_xgboost\Titanic_Classifier_xgboost_model.pkl
