# conf/pipeline/titanic.yaml
data:
  raw_data_path: data/raw
  processed_data_path: data/processed
  file_name: titanic
  id_column: PassengerId
  target_column: Survived
  test_size: 0.15
  random_state: 42

model:
  processed_data_path: ${data.processed_data_path}
  file_name: ${data.file_name}
  target_column: ${data.target_column}
  model_name: Titanic_Classifier
  model_path: models
  trained_model_path: ${model.model_path}/${model.model_name}
  optimization_params:
    n_folds: 5
    max_evals: 10
    scoring: accuracy
    hyperparameter_search:
      # XGBoost parameters
      xgboost:
        n_estimators:
          name: n_estimators
          type: int
          min: 50
          max: 200
          step: 1
        max_depth:
          name: max_depth
          type: int
          min: 3
          max: 10
          step: 1
        learning_rate:
          name: learning_rate
          type: float
          min: 0.01
          max: 0.3
        gamma:
          name: gamma
          type: float
          min: 0
          max: 0.5
        subsample:
          name: subsample
          type: float
          min: 0.6
          max: 1.0
        colsample_bytree:
          name: colsample_bytree
          type: float
          min: 0.6
          max: 1.0

      # Random Forest parameters
      random_forest:
        n_estimators:
          name: n_estimators
          type: int
          min: 50
          max: 200
          step: 1
        max_depth:
          name: max_depth
          type: int
          min: 3
          max: 20
          step: 1
        min_samples_split:
          name: min_samples_split
          type: int
          min: 2
          max: 10
          step: 1
        min_samples_leaf:
          name: min_samples_leaf
          type: int
          min: 1
          max: 4
          step: 1
        max_features:
          name: max_features
          type: str
          choices: ["auto", "sqrt", "log2"]

      # Common parameters
      random_state:
        name: random_state
        type: int
        min: 2
        max: 80
        step: 1

evaluate:
  model_name: ${model.model_name}
  model_path: ${model.model_path}
  trained_model_path: ${model.trained_model_path}
  reports_path: reports